// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutTrackerApi.Models;

namespace WorkoutTrackerApi.Migrations
{
    [DbContext(typeof(WtDbContext))]
    [Migration("20190730041406_CoupleMoreExercisesSeedData")]
    partial class CoupleMoreExercisesSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WorkoutTrackerApi.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new { Id = 1, Name = "Squat" },
                        new { Id = 2, Name = "Deadlift" },
                        new { Id = 3, Name = "Burpees" },
                        new { Id = 4, Name = "Jogging" }
                    );
                });

            modelBuilder.Entity("WorkoutTrackerApi.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DurationInMilliseconds");

                    b.Property<int>("ExerciseId");

                    b.Property<int?>("Reps");

                    b.Property<DateTime>("Timestamp");

                    b.Property<int>("UserId");

                    b.Property<int?>("WeightInGrams");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("WorkoutTrackerApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Password = "AQAAAAEAACcQAAAAEM1tKYwnVagw1a1hzyiL+oKE8WaNQiiH779QXwtusa+w63GaUEHmaFanqJao4BCuKQ==", Username = "Carson" },
                        new { Id = 2, Password = "AQAAAAEAACcQAAAAEM1tKYwnVagw1a1hzyiL+oKE8WaNQiiH779QXwtusa+w63GaUEHmaFanqJao4BCuKQ==", Username = "Dan" }
                    );
                });

            modelBuilder.Entity("WorkoutTrackerApi.Models.Set", b =>
                {
                    b.HasOne("WorkoutTrackerApi.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WorkoutTrackerApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
